### ISSUE TITLE
How to test my Scrappie

### ISSUE THREAD

**Issue by Angelven** [nanoporetech/scrappie#11]
It took me one day to install Scrappie successfully, but when I try to use it with the test fast5.file in folder ./reads/, it went wrong. 

my command was: ./build/scrappie raw reads/MINICOL228_20161012_FNFAB42578_MN17976_mux_scan_HG_52221_ch271_read66_strand.fast5 > test.fa

the error info was: 

scrappie: Failed to read raw data from dataset /Raw/Reads/Read_66/Signal.
scrappie: No basecall returned for reads/MINICOL228_20161012_FNFAB42578_MN17976_mux_scan_HG_52221_ch271_read66_strand.fast5

was it because my install was not done ? or the /Raw/ file was not downloaded?

anyone can help me ?

**Comment by tmassingham-ont** [comment]
Hello.  The command you ran looks correct and should return a fasta sequence basecall.  After compiling, could you run `make test` in your build directory please?  The whole build process should look something like:
```bash
mkdir build
cd build
cmake ..
make
make test
```

Also could you run `md5sum` or its equivalent in the reads directory please?
```bash
md5sum reads
771ef2e268f79bf522422995f1457981  reads/MINICOL228_20161012_FNFAB42578_MN17976_mux_scan_HG_52221_ch174_read172_strand.fast5
b076a321136baa0597c1592cfe597c53  reads/MINICOL228_20161012_FNFAB42578_MN17976_mux_scan_HG_52221_ch271_read66_strand.fast5
2831a6a013c93aea86bc10a181a13289  reads/test_squiggles.fa
```

**Comment by Angelven** [comment]
Thanks for your comment.
Aha, I failed 1 tests named "unittest" , errors while running CTest, does it mean my CMake was not right ?

**Comment by tmassingham-ont** [comment]
Could you provide more details about the error please?

**Comment by Angelven** [comment]
It said: 

vivien@localhost build]$ make test
Running tests...
Test project /home/vivien/Documents/Nanopore/software/scrappie-release-1.3.0/build
      Start  1: unittest
 1/14 Test  #1: unittest .........................***Failed    0.00 sec
      Start  2: test_events_call
 2/14 Test  #2: test_events_call .................   Passed    0.03 sec
      Start  3: test_raw_call
 3/14 Test  #3: test_raw_call ....................   Passed    0.01 sec
      Start  4: test_rawrgr_call
 4/14 Test  #4: test_rawrgr_call .................   Passed    0.01 sec
      Start  5: test_rawrgrgr_r94_call
 5/14 Test  #5: test_rawrgrgr_r94_call ...........   Passed    0.02 sec
      Start  6: test_rawrgrgr_r95_call
 6/14 Test  #6: test_rawrgrgr_r95_call ...........   Passed    0.01 sec
      Start  7: test_rawrnnrf_r94_call
 7/14 Test  #7: test_rawrnnrf_r94_call ...........   Passed    0.01 sec
      Start  8: test_squiggle
 8/14 Test  #8: test_squiggle ....................   Passed    0.01 sec
      Start  9: test_licence
 9/14 Test  #9: test_licence .....................   Passed    0.01 sec
      Start 10: test_help
10/14 Test #10: test_help ........................   Passed    0.00 sec
      Start 11: test_help_events
11/14 Test #11: test_help_events .................   Passed    0.00 sec
      Start 12: test_help_raw
12/14 Test #12: test_help_raw ....................   Passed    0.00 sec
      Start 13: test_help_squiggle
13/14 Test #13: test_help_squiggle ...............   Passed    0.01 sec
      Start 14: test_version
14/14 Test #14: test_version .....................   Passed    0.01 sec

93% tests passed, 1 tests failed out of 14

Total Test time (real) =   0.14 sec

The following tests FAILED:
	  1 - unittest (Failed)
Errors while running CTest
make: *** [test] Error 8

**Comment by Angelven** [comment]
BTW, md5sum test is ok

**Comment by tmassingham-ont** [comment]
Thanks.  The file `build/Testing/Temporary/LastTest.log` has more information about the failures; could you attach it please?

**Comment by Angelven** [comment]
file:///home/vivien/Documents/Nanopore/software/scrappie-release-1.3.0/build/Testing/Temporary/LastTest.log

This is my log.

**Comment by Angelven** [comment]
May I email you ?

**Comment by Angelven** [comment]
oh, I think I got the error, "libcunit.so.1: cannot open shared object file: No such file or directory", It seems my lib was not right, I will try to fix it

**Comment by tmassingham-ont** [comment]
You can email me at tim.massingham@nanoporetech.com. What operating system are you using BTW?

**Comment by Angelven** [comment]
my system is CentOS 7.0, 
Now, make test seems ok:
12/14 Test #12: test_help_raw ....................   Passed    0.00 sec
      Start 13: test_help_squiggle
13/14 Test #13: test_help_squiggle ...............   Passed    0.01 sec
      Start 14: test_version
14/14 Test #14: test_version .....................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 14

Total Test time (real) =   1.02 sec

However, a new error about HDF5 appeared:

[vivien@localhost build]$ ./scrappie raw ../reads/ > test.fa
HDF5-DIAG: Error detected in HDF5 (1.8.17) thread 0:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 969 in H5F_open(): unable to retrieve VFL class
    major: File accessibilty
    minor: Can't get value
  #002: H5FD.c line 475 in H5FD_get_class(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
scrappie: Failed to open ../reads//MINICOL228_20161012_FNFAB42578_MN17976_mux_scan_HG_52221_ch271_read66_strand.fast5 for reading.
scrappie: No basecall returned for ../reads//MINICOL228_20161012_FNFAB42578_MN17976_mux_scan_HG_52221_ch271_read66_strand.fast5
scrappie: Failed to read raw data from dataset /Raw/Reads/Read_172/Signal.
scrappie: No basecall returned for ../reads//MINICOL228_20161012_FNFAB42578_MN17976_mux_scan_HG_52221_ch174_read172_strand.fast5

**Comment by tmassingham-ont** [comment]
There seems to be a problem with the HDF5 libraries and these seem to be a different version from the ones distributed for Centos 7 via the EPEL (1.8.12 vs 1.8.17) although I don't know why a minor version change would make a difference.  How did you install them?

The following recipe works from a vanilla Centos (7.0.1406)
```bash 
yum install -y epel-release
yum install -y gcc git make cmake
yum install -y gcc CUnit CUnit-devel hdf5 hdf5-devel openblas openblas-devel
# For cblas.h
yum install -y atlas-devel
# No link for libblas.so
ln -s /usr/lib64/libopenblaso.so /usr/lib64/libblas.so

git clone --depth 1 http://github.com/nanoporetech/scrappie.git

cd scrappie
mkdir build
cd build
cmake ..
make
make test
```

**Comment by Angelven** [comment]
Sorry for my late response, follow you recipe, I have done my Scrappie well. Thanks
