### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by ragak** [nanoporetech/scrappie#14]
I am trying to run scrappie (on a linux platform), and it keeps coming up with the following error, which after a bit of searching looks like something to do with memory. Any idea if there is a quick fix, or something I'm doing wrong?

command:
scrappie raw ~/testreads > test

error:
HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 0:
Segmentation fault (core dumped)

Thank you very much!

**Comment by timmassingham** [comment]
Hi.  Could you give me a few more details about the platform version please and which HDF package was installed?
Does the error also occur when `--threads  1` is given on the command line?  There seem to be problems with some versions of HDF5 and accessing multiple files at the same time.

**Comment by ragak** [comment]
Sure thing. The OS is Centos 7.4.1708. The linux distribution is 3.10.0-693.2.2.el7.x86_64. The version of HDF5 is 1.8.12. 
And yes, it does look like --threads 1 works. Can you let me know which version of HDF5 I would need to circumvent that?
Thanks very much!

**Comment by timmassingham** [comment]
Cheers.  I'll look into the problems with HDF5 and see if I can get to the bottom of the issue but I think the fundamental reason is that, depending on what options it has been compiled with, HDF5 doesn't support being used with multiple files in the same process.  For the time being, you can get parallel processing using `parallel`.
```bash
find path/to/reads/ -name \*.fast5 | parallel -P ${OMP_NUM_THREADS} scrappie raw --threads 1 > basecalls.fa
```

Hope this helps and I'll let you know how things go.

TimM.

**Comment by tmassingham-ont** [comment]
Related to issues #8 and #11

**Comment by tmassingham-ont** [comment]
The issue relates to whether the libhdf5 library has been compiled in a thread-safe manner or not, see https://support.hdfgroup.org/HDF5/faq/threadsafe.html

The settings for Centos can be found in the file `/usr/lib64/libhdf5.settings` and looking at this file on my vanilla image suggests that this is not the case (see `Features` towards the bottom of the file).  The equivalent file on an Ubuntu system `/usr/lib/x86_64-linux-gnu/libhdf5_serial.settings` is thread safe.  All I can do is to try to detect whether a given library is thread-safe and disable threading if not.

**Comment by ragak** [comment]
Thanks, I'll try to find a different system to run it
