### ISSUE TITLE
HDF5 error

### ISSUE THREAD

**Issue by pjgmale** [nanoporetech/scrappie#23]
I am trying to run scrappie raw on the fast5 files from a Nanopore run that was stopped before the end of the basecalling. I keep running into the error below, whether I am using the fail, pass or skip files (but works perfectly with a different run that was completed). Is there something I am missing?
Thank you!

command:
scrappie raw --threads=32 myfile.fast5 > test.fa

error:
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5F.c line 586 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1384 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 360 in H5F__super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
scrappie: Failed to open myfile.fast5 for reading.
scrappie: No basecall returned for myfile.fast5
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5F.c line 586 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1384 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 360 in H5F__super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
scrappie: Failed to open myfile.fast5 for reading.
scrappie: No basecall returned for myfile.fast5

**Comment by tmassingham-ont** [comment]
What proportion of files does this effect?  The error message suggests your files are incomplete or corrupted.

**Comment by pjgmale** [comment]
Hello Tim,
So far, all the files I tested resulted in this error. How can I check for the integrity of the files?

**Comment by tmassingham-ont** [comment]
If you have `hdf5-tools` installed, `h5dump -H myfile.fast5` would be a good test as might `h5debug myfile.fast5`.
Do you also get errors if you run Scrappie with a single thread?

**Comment by pjgmale** [comment]
Thank you for your answer.
Neither h5dump nor h5debug can open the files. I also get the error when running scrappie with a single thread.
There has to be something wrong with my files, then.
