### ISSUE TITLE
cannot install scrappie python binding on macOS

### ISSUE THREAD

**Issue by alexomics** [nanoporetech/scrappie#27]
I am able to build scrappie from source, but unable to build when using `pip install scrappie` or `python3.6 setup.py install`; both return error:

    /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/smmintrin.h:561:1: note: previous definition is here
    _mm_mullo_epi32 (__m128i __V1, __m128i __V2)
    ^
    src/decode.c:25:74: error: redefinition of '_mm_mullo_epi32'
    static inline __m128i __attribute__((__gnu_inline__, __always_inline__)) _mm_mullo_epi32(const __m128i x, const __m128i y) {
                                                                             ^
I have checked that I am up-to-date with the packages suggested in #13 but this does not fix the error.

**Comment by alexomics** [comment]
Changing `-msse3` to `-msse4.1` allowed installation with lots of warnings. See here: https://stackoverflow.com/questions/43128698/inlining-failed-in-call-to-always-inline-mm-mullo-epi32-target-specific-opti

**Comment by tmassingham-ont** [comment]
Thanks.  The `_mm_mullo_epi32` function (wrapping the `PMULLD` instruction on the processor) was introduced in SSE4.1 and Scrappie has a fall-back for older processors.  For some reason clang is pulling in the function from the `smmintrin.h` but not respecting the guard around my fall-back function.  Your explicit setting of -msse4.1 is triggering the guard, skipping the fall-back.  I shall if the test can be tightened up so this doesn't happen.
