### ISSUE TITLE
Undefined reference when installing

### ISSUE THREAD

**Issue by JMiguelRamirez** [nanoporetech/scrappie#28]
Hi,
I have been trying to install scrappie in a cluster, I loaded openblas and hdf5 modules and I executed the cmake linking to these modules as stated in the README.md, using -DOPENBLAS_ROOT and -DHDF5_ROOT, but when executing the make I get:

[ 55%] Building C object CMakeFiles/scrappie.dir/src/scrappie_event_table.c.o
[ 57%] Linking C executable scrappie
CMakeFiles/scrappie.dir/src/fast5_interface.c.o: In funtion `write_annotated_events':
fast5_interface.c:(.text+0xdc5):
undefined reference to `H5P_CLS_DATASET_CREATE_ID_g'
collect2: error: ld returned 1 exit status
make[2]: *** [scrappie] Error 1
make[1]: *** [CMakeFiles/scrappie.dir/all] Error 2
make: *** [all] Error 2

It only finds one undefinied reference, and I thought that everything was correctly linked, but why does this happen? Does the problem come for the version of HDF5?

Thank you and sorry for the inconvenience,

**Comment by tmassingham-ont** [comment]
Hello.  This appear to be related to: https://github.com/Vaa3D/v3d_external/issues/1#issuecomment-192561853
The issue there is that the version of HDF5 being linked against was too old; which version of HDF5 are you using please?  Also what is the Linux (?) distribution version installed on your cluster?

**Comment by JMiguelRamirez** [comment]
I am using HDF5-1.10.1, which is not the last version available, but it should already include the symbol `H5P_CLS_DATASET_CREATE_ID_g`. And the cluster runs Scientific Linux release 7.2 (Nitrogen).
Thank you very much,

**Comment by JMiguelRamirez** [comment]
The devel package for hdf5 in the system (an old version) was removed because there was some conflict.
Also CUnit has been installed. Now it works!
