### ISSUE TITLE
RNA model?

### ISSUE THREAD

**Issue by JMiguelRamirez** [nanoporetech/scrappie#29]
Hi,

I was wondering if there is also a model for basecalling RNA from raw signal. I guess all the model options are for DNA ("raw_r94", "rgrgr_r94", "rgrgr_r941", "rgrgr_r10", "rnnrf_r94"). But I saw that it was planned #9 , so is it already implemented? Or is it going to be implemented any time soon?

**Comment by youyupei** [comment]
I have the some problem. And also, is there any model available for cDNA?

**Comment by tmassingham-ont** [comment]
Hello.  Scrappie has been superseded and all its base calling functionality is now implemented in Guppy, which should be the preferred base caller.   What use case do you have that requires Scrappie?

@youyupei  Since cDNA has been reverse transcribed, the standard DNA models in Scrappie should be appropriate but have never been validated for this use case and the trimming of the input reads will be suboptimal.  Again, Guppy would be the preferred option.

**Comment by youyupei** [comment]
@tmassingham-ont Thanks, actually I wanna use Scrappie squiggle to construct the ideal squiggle given the genomic sequences. Is Scrappie or Guppy an ideal tool to do this, or where can I find the document about the algorithm?

**Comment by tmassingham-ont** [comment]
I’ve pushed up a squiggle model for RNA, hope you find it useful.  It is important to note that the signal produced by RNA reads is considerably less ‘step-like’ than for DNA and that the assumption that each sequence context has a single, clear and repeatable level does not hold as strongly although it is good enough that raw signal maps well against the squiggle.

```
scrappie squiggle -m squiggle_r94_rna reference.fasta > squiggle_output.txt
```

**Comment by youyupei** [comment]
Thanks @tmassingham-ont , I can successfully run it now. It's very cool. btw. is there any documentation for the algorithm inside? A lot of functions in scrappie are what I want but I feel like I am using a black box.

**Comment by tmassingham-ont** [comment]
> Thanks @tmassingham-ont , I can successfully run it now. It's very cool. btw. is there any documentation for the algorithm inside? A lot of functions in scrappie are what I want but I feel like I am using a black box.

The basic architecture is stacked convolutional network, implemented in [squiggle_r94](https://github.com/nanoporetech/scrappie/blob/master/src/networks.c#L397):
All convolution window lengths are 9 and have a _tanh_ activation
- Embed the sequence into a 3 x sequence_length matrix, the coordinate of each base defined by the points of a tetrahedron.
- Convolution 3 ->32
- Repeated four times: 
  - Residual wrapper _x + f(x)_  around
    - Convolution 32 -> 32
- Convolution 32 -> 3

After transforming, the three outputs for each sequence position can be interpreted as the expected current level, variance and dwell of the samples matching that position.  The network can be trained by [Taiyaki](https://github.com/nanoporetech/taiyaki/), using a custom loss function that calculates the probability of each signal given its predicted squiggle. 

Hope this helps.

**Comment by youyupei** [comment]
It helps a lot, thanks very much!

**Comment by Psy-Fer** [comment]
Sorry to but in on this issue.
Is there any chance the changes with the RNA model can be pushed to the python2 and python3 pip wheels?
I've brought scrappie into SquiggleKit for convenience and it would simplify the install for the users. Currently they have to build from source if they wish to use the RNA model.

cheers!
James

**Comment by cjw85** [comment]
James,
I've created a new issue; we can take a look at making a new wheel.
The OPs issue seems resolved.
