### ISSUE TITLE
`make` produces an error based around `src/networks.c`

### ISSUE THREAD

**Issue by shaniAmare** [nanoporetech/scrappie#30]
Hi,

When I was trying to `make` it gives me the error below. I'm sure I am doing something really naive. If you could advise me on how to fix it, it would be great!

-----------------
`bash-4.1$ make`
`[  2%] Building C object CMakeFiles/scrappie_objects.dir/src/networks.c.o
In file included from /SourceFiles/scrappie/src/networks.c:3:`
`./SourceFiles/scrappie/src/models/raw_r94.h:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token In file included` 
     `from ./SourceFiles/scrappie/src/scrappie_structures.h:5,`
      `from ./SourceFiles/scrappie/src/networks.h:6,`
      `from ./SourceFiles/scrappie/src/networks.c:8:`
`/usr/include/inttypes.h:313: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token`
`/usr/include/inttypes.h:318: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token`
`/usr/include/inttypes.h:351: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token`
`/usr/include/inttypes.h:357: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token`
`/usr/include/inttypes.h:363: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token`
`/usr/include/inttypes.h:371: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token`
`In file included from ./SourceFiles/scrappie/src/networks.c:13:
./SourceFiles/scrappie/src/models/squiggle_r94.h:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token`
`In file included from ./SourceFiles/scrappie/src/networks.c:14:`
`./SourceFiles/scrappie/src/models/squiggle_r94_rna.h:16: error: ‘__embed_squiggle_rna_W’ undeclared here (not in a function)`
`In file included from ./SourceFiles/scrappie/src/networks.c:15:
./SourceFiles/scrappie/src/models/squiggle_r10.h:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token`
`./SourceFiles/scrappie/src/networks.c: In function ‘get_raw_model_stride’:
./SourceFiles/scrappie/src/networks.c:90: error: ‘conv_raw_stride’ undeclared (first use in this function)`
`./SourceFiles/scrappie/src/networks.c:90: error: (Each undeclared identifier is reported only once
./SourceFiles/scrappie/src/networks.c:90: error: for each function it appears in.)`
`./SourceFiles/scrappie/src/networks.c:92: error: ‘conv_rgrgr_r94_stride’ undeclared (first use in this function)`
`./SourceFiles/scrappie/src/networks.c:94: error: ‘conv_rgrgr_r941_stride’ undeclared (first use in this function)`
`./SourceFiles/scrappie/src/networks.c:96: error: ‘conv_rgrgr_r10_stride’ undeclared (first use in this function)`
`./SourceFiles/scrappie/src/networks.c:98: error: ‘conv_rnnrf_r94_stride’ undeclared (first use in this function)`
`./SourceFiles/scrappie/src/networks.c: In function ‘nanonet_raw_posterior’:`
`.SourceFiles/scrappie/src/networks.c:204: error: ‘conv_raw_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:204: error: ‘conv_raw_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:204: error: ‘conv_raw_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:209: error: ‘gruF1_raw_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:209: error: ‘gruF1_raw_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:210: error: ‘gruB1_raw_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:210: error: ‘gruB1_raw_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:213: error: ‘gruF1_raw_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:213: error: ‘gruF1_raw_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:215: error: ‘gruB1_raw_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:215: error: ‘gruB1_raw_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:220: error: ‘FF1_raw_Wf’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:220: error: ‘FF1_raw_Wb’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:220: error: ‘FF1_raw_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:223: error: ‘gruF2_raw_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:223: error: ‘gruF2_raw_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:224: error: ‘gruB2_raw_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:224: error: ‘gruB2_raw_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:226: error: ‘gruF2_raw_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:226: error: ‘gruF2_raw_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:228: error: ‘gruB2_raw_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:228: error: ‘gruB2_raw_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:234: error: ‘FF2_raw_Wf’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:234: error: ‘FF2_raw_Wb’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:234: error: ‘FF2_raw_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:238: error: ‘FF3_raw_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:238: error: ‘FF3_raw_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c: In function ‘nanonet_rgrgr_r94_posterior’:`
`.SourceFiles/scrappie/src/networks.c:259: error: ‘conv_rgrgr_r94_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:259: error: ‘conv_rgrgr_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:259: error: ‘conv_rgrgr_r94_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:263: error: ‘gruB1_rgrgr_r94_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:263: error: ‘gruB1_rgrgr_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:265: error: ‘gruB1_rgrgr_r94_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:265: error: ‘gruB1_rgrgr_r94_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:268: error: ‘gruF2_rgrgr_r94_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:268: error: ‘gruF2_rgrgr_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:270: error: ‘gruF2_rgrgr_r94_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:270: error: ‘gruF2_rgrgr_r94_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:273: error: ‘gruB3_rgrgr_r94_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:273: error: ‘gruB3_rgrgr_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:275: error: ‘gruB3_rgrgr_r94_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:275: error: ‘gruB3_rgrgr_r94_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:278: error: ‘gruF4_rgrgr_r94_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:278: error: ‘gruF4_rgrgr_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:280: error: ‘gruF4_rgrgr_r94_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:280: error: ‘gruF4_rgrgr_r94_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:283: error: ‘gruB5_rgrgr_r94_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:283: error: ‘gruB5_rgrgr_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:285: error: ‘gruB5_rgrgr_r94_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:285: error: ‘gruB5_rgrgr_r94_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:288: error: ‘FF_rgrgr_r94_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:288: error: ‘FF_rgrgr_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c: In function ‘nanonet_rgrgr_r941_posterior’:`
`.SourceFiles/scrappie/src/networks.c:308: error: ‘conv_rgrgr_r941_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:308: error: ‘conv_rgrgr_r941_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:308: error: ‘conv_rgrgr_r941_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:312: error: ‘gruB1_rgrgr_r941_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:312: error: ‘gruB1_rgrgr_r941_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:314: error: ‘gruB1_rgrgr_r941_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:314: error: ‘gruB1_rgrgr_r941_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:317: error: ‘gruF2_rgrgr_r941_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:317: error: ‘gruF2_rgrgr_r941_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:319: error: ‘gruF2_rgrgr_r941_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:319: error: ‘gruF2_rgrgr_r941_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:322: error: ‘gruB3_rgrgr_r941_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:322: error: ‘gruB3_rgrgr_r941_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:324: error: ‘gruB3_rgrgr_r941_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:324: error: ‘gruB3_rgrgr_r941_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:327: error: ‘gruF4_rgrgr_r941_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:327: error: ‘gruF4_rgrgr_r941_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:327: error: ‘gruF4_rgrgr_r941_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:329: error: ‘gruF4_rgrgr_r941_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:329: error: ‘gruF4_rgrgr_r941_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:332: error: ‘gruB5_rgrgr_r941_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:332: error: ‘gruB5_rgrgr_r941_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:334: error: ‘gruB5_rgrgr_r941_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:334: error: ‘gruB5_rgrgr_r941_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:337: error: ‘FF_rgrgr_r941_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:337: error: ‘FF_rgrgr_r941_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c: In function ‘nanonet_rgrgr_r10_posterior’:`
`.SourceFiles/scrappie/src/networks.c:357: error: ‘conv_rgrgr_r10_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:357: error: ‘conv_rgrgr_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:357: error: ‘conv_rgrgr_r10_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:361: error: ‘gruB1_rgrgr_r10_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:361: error: ‘gruB1_rgrgr_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:363: error: ‘gruB1_rgrgr_r10_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:363: error: ‘gruB1_rgrgr_r10_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:366: error: ‘gruF2_rgrgr_r10_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:366: error: ‘gruF2_rgrgr_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:368: error: ‘gruF2_rgrgr_r10_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:368: error: ‘gruF2_rgrgr_r10_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:371: error: ‘gruB3_rgrgr_r10_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:371: error: ‘gruB3_rgrgr_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:373: error: ‘gruB3_rgrgr_r10_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:373: error: ‘gruB3_rgrgr_r10_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:376: error: ‘gruF4_rgrgr_r10_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:376: error: ‘gruF4_rgrgr_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:378: error: ‘gruF4_rgrgr_r10_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:378: error: ‘gruF4_rgrgr_r10_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:381: error: ‘gruB5_rgrgr_r10_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:381: error: ‘gruB5_rgrgr_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:383: error: ‘gruB5_rgrgr_r10_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:383: error: ‘gruB5_rgrgr_r10_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:386: error: ‘FF_rgrgr_r10_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:386: error: ‘FF_rgrgr_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c: In function ‘squiggle_r94’:`
`.SourceFiles/scrappie/src/networks.c:400: error: ‘embed_squiggle_r94_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:401: error: ‘conv1_squiggle_r94_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:401: error: ‘conv1_squiggle_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:402: error: ‘conv1_squiggle_r94_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:407: error: ‘conv2_squiggle_r94_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:407: error: ‘conv2_squiggle_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:408: error: ‘conv2_squiggle_r94_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:414: error: ‘conv3_squiggle_r94_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:414: error: ‘conv3_squiggle_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:415: error: ‘conv3_squiggle_r94_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:421: error: ‘conv4_squiggle_r94_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:421: error: ‘conv4_squiggle_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:422: error: ‘conv4_squiggle_r94_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:428: error: ‘conv5_squiggle_r94_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:428: error: ‘conv5_squiggle_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:429: error: ‘conv5_squiggle_r94_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:434: error: ‘conv6_squiggle_r94_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:434: error: ‘conv6_squiggle_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:435: error: ‘conv6_squiggle_r94_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c: In function ‘squiggle_r10’:`
`.SourceFiles/scrappie/src/networks.c:514: error: ‘embed_squiggle_r10_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:515: error: ‘conv1_squiggle_r10_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:515: error: ‘conv1_squiggle_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:516: error: ‘conv1_squiggle_r10_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:521: error: ‘conv2_squiggle_r10_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:521: error: ‘conv2_squiggle_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:522: error: ‘conv2_squiggle_r10_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:528: error: ‘conv3_squiggle_r10_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:528: error: ‘conv3_squiggle_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:529: error: ‘conv3_squiggle_r10_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:535: error: ‘conv4_squiggle_r10_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:535: error: ‘conv4_squiggle_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:536: error: ‘conv4_squiggle_r10_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:542: error: ‘conv5_squiggle_r10_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:542: error: ‘conv5_squiggle_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:543: error: ‘conv5_squiggle_r10_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:548: error: ‘conv6_squiggle_r10_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:548: error: ‘conv6_squiggle_r10_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:549: error: ‘conv6_squiggle_r10_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c: In function ‘nanonet_rnnrf_r94_transitions’:`
`.SourceFiles/scrappie/src/networks.c:577: error: ‘conv_rnnrf_r94_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:577: error: ‘conv_rnnrf_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:577: error: ‘conv_rnnrf_r94_stride’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:581: error: ‘gruB1_rnnrf_r94_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:581: error: ‘gruB1_rnnrf_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:582: error: ‘gruB1_rnnrf_r94_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:582: error: ‘gruB1_rnnrf_r94_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:587: error: ‘gruF2_rnnrf_r94_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:587: error: ‘gruF2_rnnrf_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:588: error: ‘gruF2_rnnrf_r94_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:588: error: ‘gruF2_rnnrf_r94_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:593: error: ‘gruB3_rnnrf_r94_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:593: error: ‘gruB3_rnnrf_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:594: error: ‘gruB3_rnnrf_r94_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:594: error: ‘gruB3_rnnrf_r94_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:599: error: ‘gruF4_rnnrf_r94_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:599: error: ‘gruF4_rnnrf_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:600: error: ‘gruF4_rnnrf_r94_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:600: error: ‘gruF4_rnnrf_r94_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:605: error: ‘gruB5_rnnrf_r94_iW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:605: error: ‘gruB5_rnnrf_r94_b’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:606: error: ‘gruB5_rnnrf_r94_sW’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:606: error: ‘gruB5_rnnrf_r94_sW2’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:611: error: ‘FF_rnnrf_r94_W’ undeclared (first use in this function)`
`.SourceFiles/scrappie/src/networks.c:611: error: ‘FF_rnnrf_r94_b’ undeclared (first use in this function)`
`make[2]: *** [CMakeFiles/scrappie_objects.dir/src/networks.c.o] Error 1`
`make[1]: *** [CMakeFiles/scrappie_objects.dir/all] Error 2`
`make: *** [all] Error 2`

--------------------
I have all the dependencies attached to the `$PATH`.

Thanks a lot in advance,
Shani.

**Comment by tmassingham-ont** [comment]
Hello.   What environment are you trying to build in please (platform, C compiler version)?

My initial hypothesis is that your compiler does not support the `#pragma once` directive, which is at the first line of all the model files.

```
...
./SourceFiles/scrappie/src/models/raw_r94.h:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token In file included
...
./SourceFiles/scrappie/src/models/squiggle_r94.h:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token
...
```

**Comment by shaniAmare** [comment]
Thanks for the response @tmassingham-ont . I can confirm that I have loaded the module `gcc/8.1.0` in the platform `CentOS release 6.4 (Final)`.

I really appreciate your help to solve this.

Thanks a lot,
Shani.

**Comment by tmassingham-ont** [comment]
Hello.  The Docker file below works for me, with the following difference from your set-up.
* Centos 6.6 (I wasn’t able to obtain a docker image for Centos 6.4)
* gcc 8.2.1 (consequence of above)
* built Scrappie from release tar file (default git too old to be compatible with Github)

I hope this helps but, unfortunately, Scrappie is only tested on the Ubuntu platform.   Since Scrappie is provided as a research tool, rather than a product, we provided any official support for it. 

```docker
FROM centos:6.6
MAINTAINER Tim Massingham <tim.massingham@nanoporetech.com>
RUN yum install -y epel-release
RUN yum install -y gcc git make cmake

RUN yum install -y gcc CUnit CUnit-devel hdf5 hdf5-devel openblas openblas-devel
# For cblas.h
RUN yum install -y atlas-devel
RUN ln -s /usr/lib64/libopenblaso.so /usr/lib64/libblas.so

RUN yum install -y centos-release-scl
RUN yum install -y devtoolset-8-gcc

RUN yum install -y wget tar

RUN wget https://github.com/nanoporetech/scrappie/archive/release-1.4.2.tar.gz
RUN tar zxf release-1.4.2.tar.gz

RUN echo " \
    cd scrappie-release-1.4.2 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make test \
    " > build_scrappie.sh
RUN chmod +x build_scrappie.sh

RUN scl enable devtoolset-8 ./build_scrappie.sh
```

**Comment by shaniAmare** [comment]
Thanks. I'll see how to work around it.
