### ISSUE TITLE
Is the scrappy.sequence_to_squiggle in python package serve the same purpose with scrappie squiggle?

### ISSUE THREAD

**Issue by youyupei** [nanoporetech/scrappie#32]
Hi,
I am trying to use scrappie squiggle in python, so I install the python package. And I use the function scrappy.sequence_to_squiggle and try to get the same kind of result as scrappie squiggle. This is an example how I use the function:
>>>from scrappy import sequence_to_squiggle
>>> test = sequence_to_squiggle("AGGCTAGCTAGCT")
>>> test.data(as_numpy=True)

**here is the output**:

array([[ 0.4144024 , -0.15585916, -1.04943931],
       [-0.53396642, -0.86973035, -1.28983688],
       [-1.26228642, -0.67319959, -1.52632558],
       [-1.71305275,  0.49441418, -2.06113482],
       [-1.91647649,  0.90141028, -1.77614355],
       [-1.98690426, -0.42909694, -1.97921693],
       [-2.25099683, -0.52559912, -2.09264708],
       [-1.9385221 ,  0.68139863, -2.02308011],
       [-2.29804611,  0.95261008, -1.67299831],
       [-2.39523888, -0.42203459, -1.7581104 ],
       [-2.39827061, -0.62816602, -1.52443683],
       [-2.74950981,  0.41811785, -1.10415864],
       [-2.69527769,  0.20119289, -0.65440667]], dtype=float32)

It doesn't look like a same output that scrappie squiggle provides. May I ask what is the correct way to simulate a sequence inside python?

**Comment by cjw85** [comment]
A example of using these data to create a squiggle can be found here:

    https://github.com/nanoporetech/pomoxis/blob/master/pomoxis/common/simulate_calls.py#L15

That code will also immediately basecall the simulated squiggle.

Note that there is an updated implementation of squiggle simulation in [taiyaki](https://github.com/nanoporetech/taiyaki/blob/master/bin/predict_squiggle.py).

**Comment by youyupei** [comment]
Thanks very much, problem solved. A small question about the squiggle simulation in taiyaki. It is more recommended over scrappie squiggle? Thanks again for your help!!

**Comment by cjw85** [comment]
The taiyaki code is certainly more actively maintained, and in at least that sense preferred.

**Comment by ChristianMarchetta** [comment]
> 1.04943931

I'm facing the same problem as @youyupei, but unfortunately this link [](https://github.com/nanoporetech/pomoxis/blob/master/pomoxis/common/simulate_calls.py#L15) is dead and I couldn't find simulate_calls.py neither in [](https://github.com/nanoporetech/pomoxis) nor in its commit history.  Would it it be possible to have a new working link?

**Comment by youyupei** [comment]
> > 1.04943931
> 
> I'm facing the same problem as @youyupei, but unfortunately this link https://github.com/nanoporetech/pomoxis/blob/master/pomoxis/common/simulate_calls.py#L15 is dead and I couldn't find simulate_calls.py neither in https://github.com/nanoporetech/pomoxis nor in its commit history. Would it it be possible to have a new working link?

I guess the script has been moved to the dev branch: https://github.com/nanoporetech/pomoxis/blob/dev/pomoxis/common/simulate_calls.py#L15
