### ISSUE TITLE
What is the purpose of the `with h5py.File()... : pass` lines

### ISSUE THREAD

**Issue by Shians** [nanoporetech/scrappie#33]
Sorry if this is obvious, but I am not too experience with Python. In [these lines](https://github.com/nanoporetech/scrappie/blob/5db0d77d0a1583edeb12c79a4ca106b00d1224f3/python/scrappy/__init__.py#L583-L584) it appears that the file is opened and closed without doing anything, then the file is opened again inside the try statements to actually do work. Is there any reason for this particular pattern?

**Comment by cjw85** [comment]
No, I suspect this is redundant code left over from when it was written.
