### ISSUE TITLE
Update pypi wheels

### ISSUE THREAD

**Issue by cjw85** [nanoporetech/scrappie#34]
Sorry to but in on this issue.
Is there any chance the changes with the RNA model can be pushed to the python2 and python3 pip wheels?
I've brought scrappie into SquiggleKit for convenience and it would simplify the install for the users. Currently they have to build from source if they wish to use the RNA model.

cheers!
James

_Originally posted by @Psy-Fer in https://github.com/nanoporetech/scrappie/issues/29#issuecomment-510491278_

**Comment by Psy-Fer** [comment]
yes. That.
Cheers. 

Just updating my docs with all the manual install stuff. So this would be pretty great.

**Comment by cjw85** [comment]
There are now python3 scrappie-1.4.2 wheels and source distribution in pypi.
