### ISSUE TITLE
scrappie squiggle & IUPAC bases

### ISSUE THREAD

**Issue by splaisan** [nanoporetech/scrappie#36]
I have a degenerate primer with IUPAC bases which I would like to map to ONT reads
Scrappie does not seem to support IUPAC and neither N bases when generating the kmer_model

Is the only solution exploding the primer to all its possible combinations and search each individual one with SquiggleKit?

**Comment by cjw85** [comment]
SquiggleKit is using `scrappie`'s ability to simulate a squiggle from a given sequence; the sequence must necessarily be fully determined.

I'm unclear what your ultimate goal here is, if you want to identify the sequence of the primer within a read then enumeration sounds like a sensible plan.

`scrappie` is somewhat defunct in that most of its functionality has been supplanted by the functionality found in [flappie](https://github.com/nanoporetech/flappie) and [taiyaki](https://github.com/nanoporetech/taiyaki).

**Comment by splaisan** [comment]
Thanks a lot. My plan is to filter data and collect reads from gDNAseq that contain an amplicon region and work on fast5 directly to "capture" them in silico. I will do the enumeration. 😐

**Comment by Psy-Fer** [comment]
Indeed, full enumeration would be required if your goal is to essentially demultiplex by some primer sequence.

You could alternatively capture the signal next to the primer (if it's static) and go from signal to base, if you are working with signal only on this space. This has been demonstrated by someone at London calling 2019. I can get the details if you like.

**Comment by cjw85** [comment]
I'll close this issue as it is unlikely that a more direct algorithm to the @splaisan's application will be implement in `scrappie`.

**Comment by splaisan** [comment]
Just a short question,
Would it be possible to use N and thereby leave a hole of a nucleotide and therefore a hole of one position in the kmer table.
A lot of motifs (like TFBS) contain holes between matches and this would be useful elsewhere too.
I am not expert in kmer things and do not know if this is feasible, please shoot if this is not OK

Thanks for your answers, they helped and I know what to do now.

**Comment by cjw85** [comment]
The simulation **_does not_** treat the base sequence as a stream of kmers whose observed currents are then sampled independently; there are known to be rather long-range effects in terms of the sequence dependence of the observed current. As such it is not possible to leave trivially gaps in the simulated sequence; similarly simulating short sequences which in reality are embedded in a longer DNA sequence is troublesome.

**Comment by splaisan** [comment]
thanks for clarifying, this is what I feared, I will just proceed with enumeration, just fine.

**Comment by Psy-Fer** [comment]
Yea, if you have a look at the sup figures in SquiggleKit, I model the effective detection rate based on sequence length. Bottom line, lower than 30 or 40 NT, and you are gonna have a bad time.

**Comment by splaisan** [comment]
Hi @Psy-Fer, thanks for commenting about this. I need to try it of course first.
What I did so far for my first application is InSilicoPCR of gDNA reads from a public genomic seq on Promethion to select those reads (0.4%) that contain a certain region (16S in that example). This worked on fastq very well (see my at-work page: https://github.com/Nucleomics-VIB/InSilico_PCR).
I think it would be cool to be able to do the same or similar from fast5 to save the time of basecalling all the data and be able to insilico enrich a region(s) then basecall only that region. No big deal is we also capture false positive reads, the downstream analysis will handle them.
This could be applied to a gene / region / promoter of interest, a pathway of interest or any capture set one could come with. Followed by basecalling to DNA or even better searching for basemods .... (since basecalling is a moving field, this may allow reanalyse data better soon with better algorithms, especially for base modifications)
Hope I am not too much off topic here, sorry if I was ;-)

**Comment by Psy-Fer** [comment]
Are aware of the read until stuff in nature methods by Matt Loose?

**Comment by cjw85** [comment]
As we've moved beyond scrappie here, could I ask you move the discussion elsewhere?

**Comment by splaisan** [comment]
sure, sorry for that and thanks for your input
