### ISSUE TITLE
Correct sequence direction to use RNA model?

### ISSUE THREAD

**Issue by youyupei** [nanoporetech/scrappie#37]
Hi, 

A quick question regarding the `scrappy.sequence_to_squiggle` function and the "squiggle_r94_rna" model. If I am not wrong, the RNA is sequenced from 3' to 5' end. I was wondering in which direction the input sequence should be to use 'squiggle_r94_rna' model in 'sequence_to_squiggle' function?

**Comment by tmassingham-ont** [comment]
Good point!  The squiggle model is trained in the direction of the signal and so thesequence should reversed before being used.
