### ISSUE TITLE
Clarification on Parameter 'dwell' in Squiggle Output

### ISSUE THREAD

**Issue by VidurangaWijekoon** [nanoporetech/scrappie#39]
Hi,
I am trying to simulate the squiggles of some DNA sequences by using the squiggle function of scrappie. The last column of the output, 'dwell', is not completely clear for me.

Does it represent the average number of samples for that base? Since the number of samples per base seems to vary a lot, is there anyway I can also obtain the variance? And am I correct to assume that duration would then be from a normal distribution with that mean and variance?

Thanks a lot in advance for your help!

**Comment by tmassingham-ont** [comment]
Hello.  The dwell parameter is the expected number of samples for each level, modeled as a geometric distribution.  Since the geometric distribution has one parameter, this specifies both the mean and variance.  Hope this helps!

**Comment by VidurangaWijekoon** [comment]
Yes it helps a lot! Thanks a lot for the quick response!
