### ISSUE TITLE
Masking Event Detection

### ISSUE THREAD

**Issue by vickymzheng** [nanoporetech/scrappie#41]
Hello, I am currently interested in using the code that Scrappie uses for event detection. There is a portion in the event detection source code that mentions being masked out (event_detection.c line 139). It is also mentioned in the detector structures. Could someone explain what this masking is in the context of event detection? Thanks!

**Comment by tmassingham-ont** [comment]
Hello.  The event detector has two sliding-window tests, one over a short window and one over a longer window.  When an event passes through the windows, one test may exceed its threshold a sample or two after the other.  To prevent two events being called for the same actual event, the tests are prevented from creating new events ("masked")  for a short period after a new event has been detected.
