### ISSUE TITLE
Pore model for scrappie squiggle?

### ISSUE THREAD

**Issue by rrwick** [nanoporetech/scrappie#9]
I just tried out scrappie squiggle. Thank you for this - I'm sure it will be handy!

I though it was curious, however, that scrappie squiggle doesn't seem to take a model. Is it simulating both R9.4 and R9.5? Are those two pores essentially the same regarding their squiggle space?

Ryan

**Comment by tmassingham-ont** [comment]
Work in progress.  I'll make the documentation clearer but the current squiggle produced is for DNA in the R9.4 pore; I have a sketch RNA model that I'll refine and release and R9.5 should be coming soon.  R9.4 and R9.5 produce similar squiggles but are not identical.

**Comment by rrwick** [comment]
Okay, thanks. Glad to hear it's R9.4, as the reads I was trying it again ([image here](https://twitter.com/rrwick/status/932793472926433280)) are also R9.4.
